version: '3.9'
services:
  nginx:
    image: nginx
    environment:
      - CI=true
      - CHOKIDAR_USEPOLLING=true
    ports:
      - 80:80
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      - ./php:/site
          

  phpfpm:
    image: php:7.4-fpm
    volumes:
      - ./php:/site
    expose:
      - '9000'